site_name: Memento Data Engineering
theme:
  name: material

plugins:
  - search

site_url: https://y-ikli.github.io/memento

nav:
  - Accueil: index.md
  - Python:
      - Memento Python: python/memento_python.md
  - Git:
      - Memento Git: git/memento_git.md
  - Docker:
      - Memento Docker: docker/memento_docker.md
  - SQL:
      - Memento SQL: sql/memento_sql.md
  - TDD:
      - Memento TDD: tdd/memento_tdd.md
  - Clean Code:
      - Memento Clean Code: clean_code/memento_clean_code.md
