site_name: Memento Data Engineering
theme:
  name: material

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2

site_url: https://y-ikli.github.io/memento

nav:
  - Accueil: index.md
  - Python:
      - Memento Python: python/memento_python.md
      - Memento Pandas: python/memento_pandas.md      
  - SQL:
    - Memento SQL: sql/memento_sql.md
  - DBT:
    - Memento DBT: dbt/memento_dbt.md
  - Git:
      - Memento Git: git/memento_git.md
  - Docker:
      - Memento Docker: docker/memento_docker.md
  - Kubernetes:
    - Memento Kubernetes: kubernetes/memento_kubernetes.md
  - Pyspark:
      - Memento Pyspark: pyspark/memento_pyspark.md
  - TDD:
      - Memento TDD: tdd/memento_tdd.md
  - Clean Code:
      - Memento Clean Code: clean_code/memento_clean_code.md
  - Data Engineering projects:
    
      

