name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-mermaid2-plugin
          pip install pymdown-extensions

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Update markdown metadata
        run: |
          TODAY=$(date +"%Y-%m-%d")
          for file in $(find docs -name "*.md"); do
            # Remove old metadata lines
            sed -i '/^Author :/d' "$file"
            sed -i '/^Last update :/d' "$file"

            # Append fresh metadata
            echo -e "\nAuthor : Younes IKLI\nLast update : $TODAY" >> "$file"
          done
          git add docs
          git commit -m "chore: update markdown metadata [skip ci]" || echo "No changes"
          git push

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
